# lore.py


class Lore:
    """
    Holds the essential lore, world rules, and key narrative elements for the game.
    This ensures that the narrative generated by the LLM remains consistent and coherent.
    """

    def __init__(self):
        self.world_rules = self._initialize_world_rules()
        self.character_backstories = self._initialize_character_backstories()
        self.key_events = self._initialize_key_events()
        self.world_facts = self._initialize_world_facts()

    def _initialize_world_rules(self):
        """
        Defines the fundamental rules of the game world that should not be violated.
        """
        return {
            "magic": "Magic is real but only accessible through ancient artifacts.",
            "technology": "Advanced technology is present but heavily regulated by the government.",
            "society": "The city is divided into strict social classes with little mobility.",
            "time": "Time travel is theoretically possible but considered highly dangerous and forbidden."
        }

    def _initialize_character_backstories(self):
        """
        Provides backstories for key characters to maintain consistency in their actions and dialogue.
        """
        return {
            "glitch": {
                "name": "Percy Hawthorne",
                "alias": "Glitch",
                "backstory": "A former professor turned underground hacker with a mysterious past.",
                "motivations": ["uncovering the truth", "protecting her identity"]
            },
            "reggie": {
                "name": "Reginald Clive",
                "alias": "Reggie",
                "backstory": "A seasoned detective with a strict sense of justice, haunted by a past mistake.",
                "motivations": ["maintaining order", "seeking redemption"]
            },
            "arthur": {
                "name": "Sir Arthur Travers Harris",
                "alias": "Arthur",
                "backstory": "A high-ranking government official, once a military officer, now a protector of the city’s fragile order.",
                "motivations": ["preserving stability", "preventing another catastrophe"]
            }
        }

    def _initialize_key_events(self):
        """
        Lists key events in the game’s history that influence the current state of the world.
        """
        return [
            "The Collapse of 2032: A major event that led to the current dystopian state of the city.",
            "The Rise of the Corporate Guilds: Corporations took control of the government and established the current social hierarchy.",
            "The Artifact Wars: Conflicts over ancient artifacts that are the source of the world’s magic."
        ]

    def _initialize_world_facts(self):
        """
        Includes essential facts about the world that should be consistently referenced in the narrative.
        """
        return {
            "capital": "Neo-London",
            "governing_body": "The Corporate Council",
            "primary_technology": "Quantum Computing and AI",
            "common_language": "English with regional dialects"
        }

    def get_world_rules(self):
        return self.world_rules

    def get_character_backstory(self, character_name):
        return self.character_backstories.get(character_name.lower(), {})

    def get_key_events(self):
        return self.key_events

    def get_world_facts(self):
        return self.world_facts
